book:
    title:            "The Adventures of Sherlock Holmes"
    author:           "Arthur Conan Doyle"
    edition:          "First edition"
    language:         en
    publication_date: 14-10-1892

    generator: { name: easybook, version: "4.8" }

    contents:
        - { element: cover   }
        - { element: edition }
        - { element: toc     }
        - { element: lof     }
        - { element: chapter, number: I, content: chapter1.md }
        - { element: chapter, number: II, content: chapter2.md }
        - { element: chapter, number: III, content: chapter3.md }
        - { element: chapter, number: IV, content: chapter4.md }
        - { element: chapter, number: V, content: chapter5.md }
        - { element: chapter, number: VI, content: chapter6.md }
        - { element: chapter, number: VII, content: chapter7.md }
        - { element: chapter, number: VIII, content: chapter8.md }
        - { element: chapter, number: IX, content: chapter9.md }
        - { element: chapter, number: X, content: chapter10.md }
        - { element: chapter, number: XI, content: chapter11.md }
        - { element: chapter, number: XII, content: chapter12.md }
        - { element: license, content: license.md }

    editions:
        ebook:
            format:         epub
            highlight_code: false
            include_styles: true
            labels:         ["chapter"]
            theme:          clean
            toc:
                deep:       1
                elements:   ["chapter"]

        print:
            format:         pdf
            highlight_code: true
            include_styles: true
            isbn:           ~
            labels:         ["chapter"]
            margin:
                top:        20mm
                bottom:     20mm
                inner:      25mm
                outter:     20mm
            page_size:      royal-octavo
            theme:          clean
            toc:
                deep:       1
                elements:   ["chapter"]
            two_sided:      true

        web:
            format:         html
            highlight_code: true
            include_styles: true
            labels:         ["chapter"]
            theme:          clean
            toc:
                deep:       1
                elements:   ["chapter"]

        website:
            extends:        web
            format:         html_chunked
